import type { Address } from "viem";
import type { ChainKey, Profile, UlnConfig } from "./types.js";
import type { ValidationSummary } from "./validator.js";
import { DVNRegistryClient, defaultRegistry } from "./registry/index.js";

export interface SecurityMdInput {
  projectName: string;
  profile: Profile;
  deployments: ReadonlyArray<{
    srcChain: ChainKey;
    dstChain: ChainKey;
    oappAddress: Address;
    sendConfig: UlnConfig;
    receiveConfig: UlnConfig;
    summarySend: ValidationSummary;
    summaryRecv: ValidationSummary;
  }>;
  generatedAt?: Date;
  registry?: DVNRegistryClient;
  toolVersion?: string;
}

/**
 * Emits a `security.md` artifact that documents the chosen DVN configuration,
 * the profile it satisfies, and the operator diversity. Intended for the repo
 * root so that auditors / reviewers have a single pane-of-glass rather than
 * having to reconstruct config from deploy scripts.
 */
export function renderSecurityMd(input: SecurityMdInput): string {
  const registry = input.registry ?? defaultRegistry();
  const generatedAt = (input.generatedAt ?? new Date()).toISOString();
  const version = input.toolVersion ?? "secure-oapp/0.1.0";

  const lines: string[] = [];
  lines.push(`# Security configuration — ${input.projectName}`);
  lines.push("");
  lines.push(`> Generated by ${version} at ${generatedAt}. Do not edit by hand.`);
  lines.push("");
  lines.push(`**Profile:** \`${input.profile.name}\` (id \`${input.profile.id}\`)`);
  lines.push("");
  lines.push(renderProfileTable(input.profile));
  lines.push("");
  lines.push("## Deployments");
  lines.push("");

  for (const d of input.deployments) {
    lines.push(`### ${d.srcChain} → ${d.dstChain}`);
    lines.push("");
    lines.push(`- **OApp:** \`${d.oappAddress}\``);
    lines.push("");
    lines.push("**Send config**");
    lines.push(renderConfigTable(d.sendConfig, d.summarySend, d.srcChain, registry));
    lines.push("");
    lines.push("**Receive config**");
    lines.push(renderConfigTable(d.receiveConfig, d.summaryRecv, d.srcChain, registry));
    lines.push("");
  }

  lines.push("## Audit notes");
  lines.push("");
  lines.push("- This document is regenerated by `secure-oapp deploy` / `secure-oapp validate`.");
  lines.push("- The on-chain `SecureConfigBase` contract enforces these constraints at `setConfig` time, so any future change to the ULN config must re-satisfy the profile or the transaction reverts.");
  lines.push("- DVN addresses listed above are checked against the `@secure-oapp/core` registry at the time of generation. If an address is present here but later rotated upstream, the next validate run will flag it.");
  lines.push("");

  return lines.join("\n") + "\n";
}

function renderProfileTable(p: Profile): string {
  return [
    "| Constraint | Minimum |",
    "|---|---|",
    `| Required DVN count | ${p.minRequiredDVNCount} |`,
    `| Effective threshold (required + optional threshold) | ${p.minEffectiveThreshold} |`,
    `| ZK DVN count | ${p.minZkDVNCount} |`,
    `| Distinct operators | ${p.minDistinctOperators} |`,
    `| Block confirmations | ${p.minConfirmations.toString()} |`,
  ].join("\n");
}

function renderConfigTable(
  c: UlnConfig,
  s: ValidationSummary,
  chainKey: ChainKey,
  registry: DVNRegistryClient,
): string {
  const lines: string[] = [];
  lines.push(`- Confirmations: ${c.confirmations.toString()}`);
  lines.push(`- Required DVNs (${c.requiredDVNCount}):`);
  for (const dvn of c.requiredDVNs) {
    lines.push(`  - ${describeDVN(chainKey, dvn, registry)}`);
  }
  lines.push(`- Optional DVNs (${c.optionalDVNCount}, threshold ${c.optionalDVNThreshold}):`);
  if (c.optionalDVNs.length === 0) {
    lines.push(`  - _(none)_`);
  } else {
    for (const dvn of c.optionalDVNs) {
      lines.push(`  - ${describeDVN(chainKey, dvn, registry)}`);
    }
  }
  lines.push(
    `- Summary: effectiveThreshold=${s.effectiveThreshold}, zkDVNCount=${s.zkDVNCount}, distinctOperators=${s.distinctOperators}`,
  );
  return lines.join("\n");
}

function describeDVN(chainKey: ChainKey, dvn: Address, registry: DVNRegistryClient): string {
  const entry = registry.lookup(chainKey, dvn);
  if (!entry) return `\`${dvn}\` — **UNREGISTERED**`;
  const tags: string[] = [entry.operator];
  if (entry.isZk) tags.push("ZK");
  if (entry.verified) tags.push("verified");
  return `\`${dvn}\` — ${tags.join(", ")}`;
}
